services:
    # BuyBack repository
    adbuyback.repository.buyback:
        class: 'AdBuyBack\Repository\BuyBackRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'

    adbuyback.repository.buyback_image:
        class: 'AdBuyBack\Repository\BuyBackImageRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'

    # BuyBack controller
    AdBuyBack\Controller\Admin\BuyBackController:
        class: 'AdBuyBack\Controller\Admin\BuyBackController'
        arguments:
            - '@prestashop.core.command_bus'

    AdBuyBack\Controller\Admin\BuyBackImageController:
        class: 'AdBuyBack\Controller\Admin\BuyBackImageController'
        arguments:
            - '@prestashop.core.command_bus'

    # BuyBack form factory
    adbuyback.form.type.buyback:
        class: 'AdBuyBack\Form\BuyBackType'
        parent: 'form.type.translatable.aware'
        tags:
            - name: form.type

    adbuyback.form.type.buyback_image:
        class: 'AdBuyBack\Form\BuyBackImageType'
        parent: 'form.type.translatable.aware'
        arguments:
            - '@prestashop.core.query_bus'
            - '@request_stack'
        tags:
            - name: form.type

    adbuyback.form.data_provider.buyback:
        class: 'AdBuyBack\Form\BuyBackFormDataProvider'
        arguments:
            - '@prestashop.core.query_bus'

    adbuyback.form.form_builder.buyback:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
        factory: 'prestashop.core.form.builder.form_builder_factory:create'
        public: true
        arguments:
            - 'AdBuyBack\Form\BuyBackType'
            - '@adbuyback.form.data_provider.buyback'

    adbuyback.form.form_builder.buyback_image:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
        factory: 'prestashop.core.form.builder.form_builder_factory:create'
        public: true
        arguments:
            - 'AdBuyBack\Form\BuyBackImageType'
            - '@adbuyback.form.data_provider.buyback'

    adbuyback.form.data_handler.buyback:
        class: 'AdBuyBack\Form\BuyBackFormDataHandler'
        arguments:
            - '@prestashop.core.command_bus'

    adbuyback.form.form_handler.buyback:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
        factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
        arguments:
            - '@adbuyback.form.data_handler.buyback'

    # BuyBack grid factory
    adbuyback.grid.factory.definition.buyback:
        class: 'AdBuyBack\Grid\Factory\BuyBackGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

    adbuyback.grid.query_builder.buyback:
        class: 'AdBuyBack\Grid\Query\BuyBackQueryBuilder'
        parent: 'prestashop.core.grid.abstract_query_builder'
        arguments:
            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
            - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
            - '@prestashop.core.query.doctrine_search_criteria_applicator'

    adbuyback.grid.data_provider.buyback:
        class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
        arguments:
            - '@adbuyback.grid.query_builder.buyback'
            - '@prestashop.core.hook.dispatcher'
            - '@prestashop.core.grid.query.doctrine_query_parser'
            - 'buyback'

    adbuyback.grid.factory.buyback:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        public: true
        arguments:
            - '@adbuyback.grid.factory.definition.buyback'
            - '@adbuyback.grid.data_provider.buyback'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    # Buy Back domain query handler
    adbuyback.domain.buyback.query_handler.get_for_form:
        class: 'AdBuyBack\Domain\BuyBack\QueryHandler\GetBuyBackForFormHandler'
        arguments:
            - '@adbuyback.repository.buyback'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Query\GetBuyBackForForm'

    adbuyback.domain.buyback_image.query_handler.get_for_buyback:
        class: 'AdBuyBack\Domain\BuyBack\QueryHandler\GetImageForBuyBackHandler'
        arguments:
            - '@adbuyback.repository.buyback_image'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Query\GetImageForBuyBack'

    # BuyBack domain action handler
    adbuyback.domain.buyback.command_handler.create:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\CreateBuyBackHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\CreateBuyBackCommand'

    adbuyback.domain.buyback.command_handler.edit:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\EditBuyBackHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\EditBuyBackCommand'

    adbuyback.domain.buyback.command_handler.delete:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\DeleteBuyBackHandler'
        arguments:
            - '@prestashop.core.command_bus'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\DeleteBuyBackCommand'

    adbuyback.domain.buyback.command_handler.toggle_active:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\ToggleActiveBuyBackHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\ToggleActiveBuyBackCommand'

    adbuyback.domain.buyback_image.command_handler.create:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\CreateBuyBackImageHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\CreateBuyBackImageCommand'

    # BuyBack bulk handler
    adbuyback.domain.buyback.command_handler.duplicate_bulk:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\DuplicateBulkBuyBackHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\DuplicateBulkBuyBackCommand'

    adbuyback.domain.buyback.command_handler.active_bulk:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\ActiveBulkBuyBackHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\ActiveBulkBuyBackCommand'

    adbuyback.domain.buyback.command_handler.delete_bulk:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\DeleteBulkBuyBackHandler'
        arguments:
            - '@prestashop.core.command_bus'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\DeleteBulkBuyBackCommand'

    # BuyBack Image domain action handler
    adbuyback.domain.buyback_image.command_handler.delete:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\DeleteBuyBackImageHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\DeleteBuyBackImageCommand'

    adbuyback.domain.buyback_image.command_handler.delete_bulk:
        class: 'AdBuyBack\Domain\BuyBack\CommandHandler\DeleteBulkBuyBackImageHandler'
        tags:
            -   name: tactician.handler
                command: 'AdBuyBack\Domain\BuyBack\Command\DeleteBulkBuyBackImageCommand'
